### ISSUE TITLE
Modal (Pop up) 

### ISSUE THREAD

**Issue by R-fred** [pglet/pglet#101]
Is it planned for pglet to have Modals?

This would be very useful to Display confirmation dialogs or content or forms to enter information.

**Comment by FeodorFitsner** [comment]
Yes, there is Dialog control for that: https://github.com/pglet/pglet-python/blob/main/tests/test_dialog.py#L5-L13 No demo for it yet though.

**Comment by R-fred** [comment]
Thanks @FeodorFitsner , I tried it and it worked fine.
Here is a minimal example in python.

```
import pglet
from pglet import Text, Button, Stack, Dialog

def dismiss(e):
    dia.visible=False
    modal.update()

dia = Dialog(open=True, visible=False, controls=[
        Stack(controls=[Text(value="THis is a text.")]),
        Stack(controls=[
            Button(text="OK"),
            Button(text="Cancel", on_click=dismiss)
        ])
    ])

modal = Stack(controls=[dia])

def make_visible(e):
    print(dia.visible)
    print("clicked the button!")
    dia.visible=True
    modal.update()


def main(page):
    page.add(modal)
    page.add(Stack(controls=[
        Button(text="Click me and magic will happen!", on_click=make_visible)
    ]))




pglet.app("this is my app", target=main, local=True)
```

**Comment by R-fred** [comment]
One thing is I could not figure out.
If I click outside the modal it closes (all fine so far), however, next time I press the button, no modal appears.
However, if I close the modal using the _dismiss_ function (pressing the cancel button), it works as expected and I am able to get a modal once I click on the main button.

I tried adding the code of the _dismiss_ function into the _make_visible_ function in order to reproduce behaviour, without luck.

**Comment by FeodorFitsner** [comment]
It's `open` property that controls dialog visibility. This is a working example:

```python
import pglet
from pglet import Text, Button, Stack, Dialog

def dismiss(e):
    dia.open=False
    modal.update()

dia = Dialog(open=False, controls=[
        Stack(controls=[Text(value="This is a text.")]),
        Stack(controls=[
            Button(text="OK"),
            Button(text="Cancel", on_click=dismiss)
        ])
    ])

modal = Stack(controls=[dia])

def make_visible(e):
    print(dia.visible)
    print("clicked the button!")
    dia.open=True
    modal.update()


def main(page):
    page.add(modal)
    page.add(Stack(controls=[
        Button(text="Click me and magic will happen!", on_click=make_visible)
    ]))

pglet.app("this is my app", target=main, local=True)
```

**Comment by R-fred** [comment]
Works great, thanks!
