### ISSUE TITLE
errors on bash event loop

### ISSUE THREAD

**Issue by laoshaw** [pglet/pglet#108]
run greeter.sh at https://pglet.io/docs/tutorials/bash/ I got below duplicated multiple line errors:

```
pglet.sh: line 217: .events: No such file or directory
```

**Comment by FeodorFitsner** [comment]
What OS are you running it on?

**Comment by laoshaw** [comment]
ubuntu 20.04

**Comment by FeodorFitsner** [comment]
Ah, I see. The problem is in line `pglet_page "index"`. In Pglet 0.4.5 the service mode was made default where "index" page name is reserved. Change it to just `pglet_page`, so random name is used for page name:

```bash
. pglet.sh

pglet_page

pglet_send "clean"
txt_name=`pglet_send "add textbox label='Your name' description='Please provide your full name'"`
btn_hello=`pglet_send "add button primary text='Say hello'"`

while true
do
    pglet_wait_event
    if [[ "$PGLET_EVENT_TARGET" == $btn_hello && "$PGLET_EVENT_NAME" == "click" ]]; then
        name=`pglet_send "get $txt_name value"`
        pglet_send "clean page"
        pglet_send "add text value='Hello, $name!'"
        pglet_send "add text value='Close browser window to exit the program...'"
        break
    fi
done
```

Good catch. Thanks for trying Pglet!

**Comment by FeodorFitsner** [comment]
@laoshaw it's been kind of surprising (and pleasant) to see a sudden spike in Pglet usage, so may I ask where did you know about Pglet and what kind of app are you working on and what language? We are still trying to better understand Pglet use cases and need to plan an upcoming release for any new/breaking changes.

**Comment by laoshaw** [comment]
https://messaged.com/tldr/newsletter is where I learned it. I actually was trying to see what pglet really does but was paused due to the mentioned bug. Anything making UI easy will find its audience I think.

**Comment by FeodorFitsner** [comment]
Oh, great, thank you!
