### ISSUE TITLE
Custom components?

### ISSUE THREAD

**Issue by isaiahtaylor** [pglet/pglet#109]
Feature request: add custom components to a pglet server, preferably using YAML or similar. Love the project!

**Comment by FeodorFitsner** [comment]
@isaiahtaylor thanks for trying Pglet and sorry for the delay with reply! I've been thinking about **components** as something made of existing **controls** and could be re-used on multiple pages/apps. Something like "Login" component made of two Textbox and a "Sign in" Button controls. What do you understand under "component"? Is there any React components you are missing to build the app? Also, as we are still trying to better understand Pglet users - may I ask where did you know about Pglet? What kind of app(s) are you building?
