### ISSUE TITLE
ToDo app: Page name already taken error.

### ISSUE THREAD

**Issue by Rockwell70** [pglet/pglet#110]
I've gotten to the Python tutorial step in which we create the reusable TodoApp class and when I run the code I get the following error:

level=fatal msg="Connect app error: Page name is already taken"

I tried writing my own code following the example and then copied the example code, and the result was the same in both cases.

Do I need to create a config file to make this work, or should it work on its own?

Cheers,
[todo.txt](https://github.com/pglet/pglet/files/7614142/todo.txt)

**Comment by Rockwell70** [comment]
I figured the issue: the last line of tutorial code:

pglet.app("todo-app", target=main)

works if you remove "-app"

pglet.app("todo", target=main)

**Comment by FeodorFitsner** [comment]
Thanks for the update and trying Pglet!

Honestly, it's been kind of surprising (and pleasant) to see a sudden spike in Pglet usage, so may I ask where did you know about Pglet and what kind of app are you working on and what language? We are still trying to better understand Pglet use cases and need to plan an upcoming release for any new/breaking changes.

**Comment by Rockwell70** [comment]
Hello, I’m really enjoying working with Pglet. I learned about it from the TLDR daily email, which highlights at least two cool new libraries everyday. I’m working in Python and modifying the todo list demo a bit so I can use it for my boss. He’s obsessed with task lists, so Pglet is the perfect solution.

**Comment by FeodorFitsner** [comment]
Cool, thanks for letting know!
