### ISSUE TITLE
Gave up connecting to Client service

### ISSUE THREAD

**Issue by eperezvcc** [pglet/pglet#115]
Hi,

I'm new to pglet. I have the latest version 0.4.6 and I'm trying the simplest code possible that I could find:

import pglet
from pglet import Text

page = pglet.page("my-app", local=True) # this page will start a local Pglet server
page.add(Text('Hello, localhost!'))

I'm using python3 and it was installed with pip3. The error is always:

`python3 hello.py                                                                                                                                        1 err  17:36:03 
FATA[2021-12-08T17:36:12+01:00] Gave up connecting to Client service after 20 attemps 
Traceback (most recent call last):
  File "/Users/eperez/Documents/workspace/python/pglet/hello.py", line 4, in <module>
    page = pglet.page("my-app", local=True) # this page will start a local Pglet server
  File "/usr/local/lib/python3.9/site-packages/pglet/pglet.py", line 42, in page
    exe_result = subprocess.check_output(pargs).decode("utf-8").strip()
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/lib/python3.9/site-packages/pglet/bin/darwin-amd64/pglet', 'page', 'my-app', '--local', '--all-events']' returned non-zero exit status 1.`

I'm using Mac OS (latest version too) and I just want to work with local server on my machine.

Thank you.

**Comment by FeodorFitsner** [comment]
Thanks for trying Pglet!

Is it a Mac with M1 CPU?

What if you run `/usr/local/lib/python3.9/site-packages/pglet/bin/darwin-amd64/pglet page my-app --local` from command line? What results/errors do you get?

**Comment by eperezvcc** [comment]
> Thanks for trying Pglet!
> 
> Is it a Mac with M1 CPU?
> 
> What if you run `/usr/local/lib/python3.9/site-packages/pglet/bin/darwin-amd64/pglet page my-app --local` from command line? What results/errors do you get?

Hi! 

Nope, it's an i7. I tried running the pglet binary directly from that path and I got the same error:

`FATA[2021-12-09T07:03:44+01:00] Gave up connecting to Client service after 20 attemps`

Thanks!

**Comment by FeodorFitsner** [comment]
OK, what if you run `/usr/local/lib/python3.9/site-packages/pglet/bin/darwin-amd64/pglet server`?

**Comment by FeodorFitsner** [comment]
Please feel free to re-open the issue if you are still experiencing it with the latest Pglet version.
