### ISSUE TITLE
Add blur event for controls

### ISSUE THREAD

**Issue by mikaelho** [pglet/pglet#118]
Feature request: Add on_blur or similar event for controls to enable action when user navigates away from the control.

Why: Possible to create more responsive applications.

**Comment by FeodorFitsner** [comment]
Thank you for the suggestion! Could you give me a short-list of controls (in the order of priority) you'd like to see blur event implemented in the first place?

**Comment by mikaelho** [comment]
Looking closer to this, looks like my test had a bug and the `on_change` works fine for my use cases. Apologies for the noise.
