### ISSUE TITLE
Expose change event separately for text inputs

### ISSUE THREAD

**Issue by mikaelho** [pglet/pglet#119]
**Currently**

Seems that the `on_change` event of `Textbox` is triggered by the `input` js event (i.e. while typing), and not triggered by the `change` js event (e.g. while pressing enter or navigating away from the control. You can experiment with this [here](https://replit.com/@mikaelho/pglet-textbox-events).

**Issue**

If I want to clean up the control value in the event handler, e.g. stripping extra white space from beginning and end. As the event is triggered on input, with this cleaning operation I can no longer enter whitespace, i.e. the space between words, without resorting to gymnastics like first typing the words together and then going back to insert the space.

**Request**

It would be nice if we have `on_input` and `on_change` separately, corresponding to the standard HTML/js logic for clarity. This same would apply to all controls using the HTML `<input>` tag as the underlying element (`SpinButton` etc.)

This might break some of the current samples, but the fix should be relatively simple in most cases, just add the same handler to `on_input` that you might now have for `on_change`.

**Comment by FeodorFitsner** [comment]
Pglet uses Fluent UI library by Microsoft. I'm looking at the [docs for Textfield control](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) and description to `onChange` event says "*Callback for when the input value changes. This is called on both **input** and **change** events. (In a later version, this will probably only be called for the change event.)*". Well, as a workaround, you can cleanup the value at the moment it's used, say on a click of "Save" button. Alternatively, we pglet could trim whitespace automatically. Not sure if that should be default behaviour though...

**Comment by mikaelho** [comment]
Thanks, understanding that I can check the Fluent docs in the background helps with a lot of things.

Maybe the best approach to manage the current setup would be to have a configurable timeout -- only forward the `on_change` event after the user has not typed in 300-500 ms. ... No, not a good idea: watching myself as I type this, I do type a comma or a period, then the space, then often stop to think about the next sentence -- it would be very annoying if the clean-up came around and removed the space at that point.

I think I will just forget about changing values on validation, for now. It is preventing me from using some of the power of the validation package, but seems the lesser evil.

**Comment by FeodorFitsner** [comment]
Fluent `Textfield` itself has some validation framework - I haven't explored it yet. And there is also masked input support which could be interesting for some scenarious.
