### ISSUE TITLE
Auto switch tabs

### ISSUE THREAD

**Issue by pinkuuu1** [pglet/pglet#130]
FEATURE REQUEST

Hi there!

I've been using your amazing library for a small personal project and i'm loving it, thank you for your hard work.

There is one feature that would be amazing if it could be implemented some how, auto switching of tabs or having a function to switch to another tab under the same tabs variable.

**Comment by mikaelho** [comment]
I do not think that it is really documented or demonstrated anywhere, but you can switch tabs by setting the `value` of the `Tabs` control to the `text` of the `Tab` you want to switch to (+ update).

**Comment by pinkuuu1** [comment]
Thank you very much haha this solved it for me, i can close this now :).
