### ISSUE TITLE
Change web page icon

### ISSUE THREAD

**Issue by pinkuuu1** [pglet/pglet#132]
FEATURE:

Add support for setting web page icons, changing it from the default pglet icon.

**Comment by pinkuuu1** [comment]
Okay after looking at adding this and #133 I'm pretty lost as i've never touched TypeScript in my entire life haha, my initial idea to implement it was messy and confusing

**Comment by FeodorFitsner** [comment]
No worries, I'll give a thought how it could be better implemented.
