### ISSUE TITLE
Failed to parse control attribute value if ends on a double quote

### ISSUE THREAD

**Issue by FeodorFitsner** [pglet/pglet#42]

**Comment by c-nv-s** [comment]
Thank goodness I spotted this ticket.
I think I just spent a total of about 5 hours trying various forms of escaping quotes to figure out why pglet kept only returning the first word for any command along the lines of:
```
pglet_add "text value=$( httpie GET my.site/api/v1  Header "Authorization:Bearer ${TOKEN}" |  jq '.result'  ) "
```
happy to set up a set of example results when I have a bit more time or if the issue remains after the next update

**Comment by FeodorFitsner** [comment]
Oh, I feel sorry you've spent so much time fighting with this bug! It's been really annoying to fix as well :) I'm going to update the docs explaining all possible quotes (and other escapes) in attr values.

**Comment by FeodorFitsner** [comment]
We've just released Pglet v0.2.2 with this bug fixed. Could you please give it a try and let me know how it worked.

**Comment by c-nv-s** [comment]
thanks! i will try when I have some time

**Comment by FeodorFitsner** [comment]
btw, besides Bash what else language would you consider for doing stuff with Pglet?

**Comment by c-nv-s** [comment]
Golang.
I don't know if you should close this ticket just yet, I'm testing this now and still seem to be having difficulties

**Comment by FeodorFitsner** [comment]
Sure, let me know about your findings and we'll re-open it if there is still an issue.

**Comment by c-nv-s** [comment]
so maybe you can correct me if I have the wrong expectations.

first command:
```
$ curl http://echo.jsontest.com/key/value/one/two 
{
   "one": "two",
   "key": "value"
}
```

above result is expected output for:
```
pglet_add "text value=$( curl http://echo.jsontest.com/key/value/one/two )"
```
actual result is just blank.

second command:
```
$ curl http://echo.jsontest.com/key/value/one/two | jq '.one'
"two"
```

above result is the expected output from :
```
pglet_add "text value=$( curl http://echo.jsontest.com/key/value/one/two | jq '.one' )"
```

actual result :
```
echo
```

This is without even starting to pass in variables or escape double quotes within the commands.
or am I approaching this incorrectly?

**Comment by FeodorFitsner** [comment]
Ah, good stuff! Love Bash for its brain-teasing properties :)

Right, new lines and quotes must be escaped to build Pglet command as entire command should be a single line. Also, if there are spaces in attribute values they must be surrounded by single or double quotes.

For example you want to add a `text` control with the following contents:

```
Line 1
Line's 2
Line "3"
```

Command should look like:

```
pglet_add "text pre value=\"Line 1\nLine's 2\nLine \\\"3\\\"\""
```

(I'm adding `pre` to see new lines)

Therefore, we can have some helper functions doing escaping for us:

```bash
function escape_str() {
  CR="
"
  local r1="${$1//${CR}/\\\n}"
  #echo ${r1//\"/\\\"} # escape double quotes
  echo ${r1//\'/\\\'} # escape single quotes
}

function escape_cmd() {
  CR="
"
  local result=`$@`
  local r1="${result//${CR}/\\\n}"
  #echo ${r1//\"/\\\"} # escape double quotes
  echo ${r1//\'/\\\'} # escape single quotes
}
```

`escape_str()` takes a string as a parameter while `escape_cmd()` takes a command, runs it and then escapes the results. Both functions escape single quotes, so command attrs should be surrounded with single quotes.

Example:

```bash
function main() {
  local t=$(escape_cmd curl http://echo.jsontest.com/key/value/one/two)
  pglet_send "add text pre value='$t'"
}

pglet_app "index" "main"
```

Watch it live at repl.it: https://repl.it/@pglet/bash-curl-pglet

Would it make sense to add this helpers to `pglet.sh`?

...I've started working on Go client library for Pglet - stay tuned!

**Comment by c-nv-s** [comment]
wow! so that was impressively quick.
I was looking into whether there might be a solution by passing ``$@`` or ``$*`` or even ``printf "%q" ${1}`` as a way around it but I think you nailed it with the escaping functions.
Seems sensible to add these functions as helpers yes!
Let me know and i'll update and run more test to see if I can find some edge cases etc.
Amazing work

**Comment by FeodorFitsner** [comment]
I'll update the helper and docs.

Sure, if you can provide more use cases that would be awesome!

**Comment by c-nv-s** [comment]
I'm going to request a feature for adding iframes

**Comment by FeodorFitsner** [comment]
What would be the use case for that (need to understand min props for the control)?

**Comment by c-nv-s** [comment]
What I had in mind was if I use pglet to build a dashboard or a kiosk, one might want to display information from an existing internal site or resource "as is" ( in a dumb frame... or even interactive frame now I think about it). the piglet command would allow a user to set the dimensions of the iframe at a minimum or to be responsive within a stack component.
make sense?

**Comment by FeodorFitsner** [comment]
Sure, that makes sense. I've added a new issue for iframe control: https://github.com/pglet/pglet/issues/59

**Comment by c-nv-s** [comment]
> Example:
> 
> ```shell
> function main() {
>   local t=$(escape_cmd curl http://echo.jsontest.com/key/value/one/two)
>   pglet_send "add text pre value='$t'"
> }
> 
> pglet_app "index" "main"
> ```
> 
> Watch it live at repl.it: https://repl.it/@pglet/bash-curl-pglet
> 

Could it be possible for a user to change the response header to add e.g. `` Content-Type: application/json ``
to help consumers ?

**Comment by FeodorFitsner** [comment]
You mean Pglet page response?
