### ISSUE TITLE
PubSub commands

### ISSUE THREAD

**Issue by FeodorFitsner** [pglet/pglet#80]
For making chat-like experiences.

**Comment by c-nv-s** [comment]
I'm curious if this could be also be useful if you wanted to allow for detecting swipe events? e.g. in a kiosk type application
The backend client could subscribe to a "swipe-events" channel, and the frontend could publish swipe-up, swipe-down, swipe-left and swipe-right events to the channel?

**Comment by c-nv-s** [comment]
wait a minute, I'm guessing you actually mean pubsub for the frontend? for the frontend to subscribe to messages published from the backend clients?... I'm a little confused which way around this is?

**Comment by FeodorFitsner** [comment]
It's for the app being able to communicate between the sessions (of the same app).

First, we are going to add events when a new session started and ended, so in your app you can know the number of connected users and there is a way to identify them. Second, there would be a command to send messages to different sessions and those sessions will receive those messages as events.

**Comment by c-nv-s** [comment]
Oh I get it. Very nice!
