### ISSUE TITLE
Run HTML code as part of pglet App - Example: embed video in pglet App

### ISSUE THREAD

**Issue by R-fred** [pglet/pglet#91]
Is there a way to run arbitrary HTML code in pglet?
As an example streamlit has that ability via an option "run_unsafe_html"

In particular I am interested in embedding videos.

**Comment by FeodorFitsner** [comment]
Sure, we can add that. Thanks for the suggestion!

**Comment by FeodorFitsner** [comment]
What client library do you use, btw?

**Comment by R-fred** [comment]
I am using the Python Library.
Very nice and lightweight, the Lack of dependencies is a clear plus for me.

**Comment by FeodorFitsner** [comment]
Cool, I'm glad you like it! Just curious, what kind of app are you working on?

**Comment by R-fred** [comment]
Right now I am just trying it, seeing if I can use it for my own needs. Looks good so far :).
For the video specifically I am building a doorbell with video camera, so I would need a way to display videos.

I like how easy it is with pglet to make nice looking apps. A massive plus, as I said before, is the standalone character. By the way, I could install it no problems on a Macbook Air M1. The same cannot be said of alternatives that need a lot of dependencies. :-)

**Comment by FeodorFitsner** [comment]
Thank you for the great feedback!

**Comment by FeodorFitsner** [comment]
A new release with "Html" control support (and built-in authentication/authorization) is coming this week.

**Comment by R-fred** [comment]
Looking forward to testing it
